# Generated by Django 4.1.4 on 2023-01-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todayapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1897-02-23'),
            preserve_default=False,
        ),
    ]
