# Generated by Django 4.1.4 on 2023-01-10 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='desC',
            new_name='desc',
        ),
    ]
