# Generated by Django 4.1.4 on 2023-01-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_rename_desc_film_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='img',
            field=models.ImageField(default='ghsdg', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
