# Generated by Django 4.1.4 on 2023-01-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveloapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
