# Generated by Django 4.1.4 on 2023-01-06 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_travel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='descri',
            new_name='des',
        ),
    ]
