# Generated by Django 4.1.4 on 2023-01-07 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_rename_des_travel_des1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Travel',
            new_name='Person',
        ),
    ]
