# Generated by Django 4.1.4 on 2023-01-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='active',
            field=models.BooleanField(),
        ),
        migrations.AlterModelTable(
            name='cart',
            table='Cart',
        ),
    ]
