# Generated by Django 4.1.4 on 2023-01-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_alter_cartitem_active_alter_cart_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
